
export const images = {
    iconHome:require("../assets/icons/home.png"),
    iconHomeFilled:require("../assets/icons/homeFilled.png"),
    iconHeart:require("../assets/icons/heart.png"),
    iconHeartFilled:require("../assets/icons/heartFilled.png"),
    iconCart:require("../assets/icons/cart.png"),
    iconCartFilled:require("../assets/icons/cartFilled.png"),
    iconBag:require("../assets/icons/bag.png"),
    iconBagFilled:require("../assets/icons/bagFilled.png"),
    iconProfileFilled:require("../assets/icons/profileFilled.png"),
    iconProfile:require("../assets/icons/profile.png"),
    bannerImage:require("../assets/images/banner.png"),
    iconSort:require("../assets/icons/sort.png"),
    iconRow:require("../assets/icons/row.png"),
    iconSwap:require("../assets/icons/swap.png"),
    iconGrid:require("../assets/icons/grid.png"),
    iconBack:require("../assets/icons/back.png"),
    iconSearch:require("../assets/icons/search.png"),
    iconStarYellow:require("../assets/icons/starYellow.png"),
    iconStar:require("../assets/icons/star.png"),
}